In [9]:
import numpy as np
import gym
import random

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [5]:
q_table = np.zeros([state_size,action_size])
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# System parameters
total_episodes = 15000
max_steps = 100
learning_rate = 0.8
gamma = 0.95

In [7]:
# Exploration Tradeoff parameters
epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

In [11]:
type(env.action_space)

gym.spaces.discrete.Discrete

In [ ]:
rewards = []
for episode in range(total_episodes):
  # Step one : Reset the environment
  state = env.reset()
  step = 0
  done = False
  total_rewards = 0

  # Step2 : Continue the steps 3-5 till learning is stop or termination step is reached
  for step in range(max_steps):
    # Step 3 : The exploration versus exploitation trade-off
    number = random.uniform(0,1)

    ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
    if number > epsilon:
      action = np.argmax(q_table[state,:])

    # Else doing a random choice --> exploration
    else:
      action = env.action_space.sample()

    # Take the action (a) and observe the outcome state(s') and reward (r)
    new_state, reward, done, _ = env.step(action)

    total_rewards += reward

    C = reward + gamma*np.max(q_table[new_state,:]) - q_table[state,action]
    q_table[state,action] = q_table[state,action] + learning_rate*C

    # Our new state is state
    state = new_state

    # If done (if we're dead) : finish episode
    if done:
      break
  epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
  rewards.append(total_rewards)

In [15]:
print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(q_table)

Score over time: 0.4706666666666667
[[2.46952193e-01 2.88289968e-02 2.89747242e-02 4.30072003e-02]
 [2.31314473e-03 7.10400692e-03 5.97107915e-04 8.45675863e-02]
 [7.10424194e-03 1.23878056e-02 2.69829365e-03 2.30888327e-02]
 [3.50759350e-03 9.11162146e-05 7.00913298e-04 2.04495705e-02]
 [3.74956957e-01 8.14832711e-03 9.90188771e-03 1.76754136e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.55653615e-04 2.81594608e-06 1.79387427e-04 2.24197705e-07]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.69451290e-05 4.21464971e-02 1.90561280e-02 5.87872830e-01]
 [8.87307536e-03 6.56647754e-01 5.32965856e-04 1.33348015e-02]
 [1.39955784e-01 1.18373704e-03 1.38413636e-04 1.51970826e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.40879754e-02 7.08450384e-03 7.95610201e-01 4.81786910e-03]
 [2.24506912e-01 9.66173313e-01 1.76374480e-01 1.14013412e-01]
 [0.00000000e+00 0.

In [18]:
env.reset()

for episode in range(20):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(q_table[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 13
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 30
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 99
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 34
****************************************************
EPISODE  4
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 99
****************************************************
EPISODE  5
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 54
****************************************************
EPISODE  6
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 35
****************************************************
EPISODE  7
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 19
****************************************************
EPISODE  8
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of s